#spring:
#  application:
#    name: ad-eureka
#
#server:
#  port: 8000
#
#eureka:
#  instance:
#    hostname: localhost
#  client:
#    # 是否从eureka server获取信息(单节点,不需要同步其他节点数据,没有其他eureka server)
#    fetch-registry: false
#    # 是否将自己注册到eureka上(它自己就是eureka)
#    register-with-eureka: false
#    # 需要依赖的地址
#    service-url:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

---
spring:
  application:
    name: ad-eureka
  profiles: server1 #不同的服务名字指向同一个ip地址
server:
  port: 8000
eureka:
  instance:
    hostname: server1
    prefer-ip-address: false
  client:
    service-url:
      defaultZone: http://server2:8001/eureka/,http://server3:8002/eureka/

---
spring:
  application:
    name: ad-eureka
  profiles: server2 #不同的服务名字指向同一个ip地址
server:
  port: 8001
eureka:
  instance:
    hostname: server2
    prefer-ip-address: false
  client:
    service-url:
      defaultZone: http://server1:8000/eureka/,http://server3:8002/eureka/

---
spring:
  application:
    name: ad-eureka
  profiles: server3 #不同的服务名字指向同一个ip地址
server:
  port: 8002
eureka:
  instance:
    hostname: server3
    prefer-ip-address: false
  client:
    service-url:
      defaultZone: http://server1:8000/eureka/,http://server2:8001/eureka/
